name: asynctools
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        branch: [master]
        target:
          - os: linux
            cpu: amd64
            nim_version: devel
          - os: linux
            cpu: amd64
            nim_version: 1.2.12
          - os: linux
            cpu: amd64
            nim_version: 1.4.8
          - os: linux
            cpu: i386
            nim_version: devel
          - os: linux
            cpu: i386
            nim_version: 1.2.12
          - os: linux
            cpu: i386
            nim_version: 1.4.8
          - os: macos
            cpu: amd64
            nim_version: devel
          - os: macos
            cpu: amd64
            nim_version: 1.2.12
          - os: macos
            cpu: amd64
            nim_version: 1.4.8
          - os: windows
            cpu: amd64
            nim_version: devel
          - os: windows
            cpu: amd64
            nim_version: 1.2.12
          - os: windows
            cpu: amd64
            nim_version: 1.4.8
          - os: windows
            cpu: i386
            nim_version: devel
          - os: windows
            cpu: i386
            nim_version: 1.2.12
          - os: windows
            cpu: i386
            nim_version: 1.4.8
        include:
          - target:
              os: linux
            builder: ubuntu-latest
          - target:
              os: macos
            builder: macos-latest
          - target:
              os: windows
            builder: windows-latest

    name: '${{ matrix.target.os }}-${{ matrix.target.cpu }}-nim-${{ matrix.target.nim_version }} (${{ matrix.branch }})'
    runs-on: ${{ matrix.builder }}

    steps:
      - name: Checkout asynctools
        uses: actions/checkout@v4
        with:
          path: asynctools
          submodules: false

      - name: Setup Nim
        uses: iffy/install-nim@v5
        with:
          version: ${{ matrix.target.nim_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run asynctools tests
        shell: bash
        working-directory: asynctools
        run: |
          nimble install -y
          nimble test
