name: asynctools
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        branch: [master]
        target:
          - os: linux
            cpu: amd64
            nim_branch: devel
          - os: linux
            cpu: amd64
            nim_branch: v1.2.12
          - os: linux
            cpu: amd64
            nim_branch: v1.4.8
          - os: linux
            cpu: i386
            nim_branch: devel
          - os: linux
            cpu: i386
            nim_branch: v1.2.12
          - os: linux
            cpu: i386
            nim_branch: v1.4.8
          - os: macos
            cpu: amd64
            nim_branch: devel
          - os: macos
            cpu: amd64
            nim_branch: v1.2.12
          - os: macos
            cpu: amd64
            nim_branch: v1.4.8
          - os: windows
            cpu: amd64
            nim_branch: devel
          - os: windows
            cpu: amd64
            nim_branch: v1.2.12
          - os: windows
            cpu: amd64
            nim_branch: v1.4.8
          - os: windows
            cpu: i386
            nim_branch: devel
          - os: windows
            cpu: i386
            nim_branch: v1.2.12
          - os: windows
            cpu: i386
            nim_branch: v1.4.8
        include:
          - target:
              os: linux
            builder: ubuntu-18.04
          - target:
              os: macos
            builder: macos-10.15
          - target:
              os: windows
            builder: windows-2019

    name: '${{ matrix.target.os }}-${{ matrix.target.cpu }}-nim-${{ matrix.target.nim_branch }} (${{ matrix.branch }})'
    runs-on: ${{ matrix.builder }}
    env:
      NIM_DIR: nim-${{ matrix.target.nim_branch }}-${{ matrix.target.cpu }}
      NIM_BRANCH: ${{ matrix.target.nim_branch }}
      NIM_ARCH: ${{ matrix.target.cpu }}

    steps:
      - name: Checkout asynctools
        uses: actions/checkout@v4
        with:
          path: asynctools
          submodules: false

      - name: Setup Nim
        uses: iffy/install-nim@v5
        with:
          version: ${{ matrix.nimversion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run asynctools tests
        shell: bash
        working-directory: asynctools
        run: |
          nimble install -y
          nimble test
